



import { FontOption, ReaderSettings, ShortcutMap, ReadingMode } from './types';

export const ARABIC_FONTS: FontOption[] = [
  { name: 'Amiri Quran', family: '"Amiri Quran", serif', isQuranic: true },
  { name: 'Amiri (Classic)', family: '"Amiri", serif', isQuranic: true },
  { name: 'Scheherazade New', family: '"Scheherazade New", serif', isQuranic: true },
  { name: 'Lateef', family: '"Lateef", serif', isQuranic: true },
  { name: 'Noto Naskh Arabic', family: '"Noto Naskh Arabic", serif', isQuranic: true },
  { name: 'Katibeh', family: '"Katibeh", serif', isQuranic: true },
  { name: 'Harmattan', family: '"Harmattan", sans-serif', isQuranic: true },
  { name: 'Markazi Text', family: '"Markazi Text", serif', isQuranic: true },
  { name: 'Kufam', family: '"Kufam", sans-serif', isQuranic: true },
  { name: 'Cairo', family: '"Cairo", sans-serif' },
  { name: 'Tajawal', family: '"Tajawal", sans-serif' },
  { name: 'Almarai', family: '"Almarai", sans-serif' },
  { name: 'Aref Ruqaa', family: '"Aref Ruqaa", serif' },
  { name: 'IBM Plex Sans Arabic', family: '"IBM Plex Sans Arabic", sans-serif' },
  { name: 'Mada', family: '"Mada", sans-serif' },
  { name: 'Reem Kufi', family: '"Reem Kufi", sans-serif' },
  { name: 'El Messiri', family: '"El Messiri", sans-serif' },
  { name: 'Lalezar', family: '"Lalezar", system-ui' },
  { name: 'Changa', family: '"Changa", sans-serif' },
  { name: 'Mirza', family: '"Mirza", serif' },
];

export const TEXT_COLORS = [
  { name: 'Black', value: '#000000' },
  { name: 'White', value: '#ffffff' },
  { name: 'Slate', value: '#e2e8f0' },
  { name: 'Gray', value: '#9ca3af' },
  { name: 'Zinc', value: '#a1a1aa' },
  { name: 'Neutral', value: '#a3a3a3' },
  { name: 'Stone', value: '#a8a29e' },
  { name: 'Cream', value: '#fef3c7' },
  { name: 'Red', value: '#ef4444' },
  { name: 'Orange', value: '#f97316' },
  { name: 'Amber', value: '#fbbf24' },
  { name: 'Yellow', value: '#facc15' },
  { name: 'Lime', value: '#a3e635' },
  { name: 'Green', value: '#4ade80' },
  { name: 'Emerald', value: '#34d399' },
  { name: 'Teal', value: '#2dd4bf' },
  { name: 'Cyan', value: '#22d3ee' },
  { name: 'Sky', value: '#38bdf8' },
  { name: 'Blue', value: '#60a5fa' },
  { name: 'Indigo', value: '#818cf8' },
  { name: 'Violet', value: '#a78bfa' },
  { name: 'Purple', value: '#c084fc' },
  { name: 'Fuchsia', value: '#e879f9' },
  { name: 'Pink', value: '#f472b6' },
  { name: 'Rose', value: '#fb7185' },
  { name: 'Brown', value: '#a16207' },
];

export const ALL_READING_MODES: ReadingMode[] = [
  'typewriter', 
  'rsvp', 
  'highlight', 
  'spotlight', 
  'magnify', 
  'scroller', 
  'karaoke', 
  'bounce', 
  'pulse',
  'blur',
  'wavy',
  'glitch',
  'gradient',
  'outline',
  'neon',
  'mirror',
  'jelly', // Replaced
  'flash',
  'dim',
  'boxed',
  'underline',
  'marker',
  'thick',
  'shake',
  'swing', // Replaced
  'slideDown' // Replaced
];

export const DEFAULT_SHORTCUTS: ShortcutMap = {
  togglePlay: ' ',
  prevWord: 'ArrowLeft',
  nextWord: 'ArrowRight',
  incFontSize: 'g',
  decFontSize: 's',
  incSpeed: 'i',
  decSpeed: 'd',
  toggleFullscreenApp: 'Shift',
  toggleFullscreenReader: 'z',
  incBrightness: 'ArrowUp',
  decBrightness: 'ArrowDown',
  reset: 'r',
  nextFont: 'f',
  nextColor: 'c',
  incGlow: ']',
  decGlow: '[',
  toggleBold: 'b',
  toggleLang: 'l',
  nextMode: 'm',
  toggleEdit: 'e',
  clearText: 'Delete',
  togglePomodoro: 'p',
  toggleLibrary: 'o',
  toggleShortcuts: 'h',
  toggleStats: 't',
};

export const DEFAULT_SETTINGS: ReaderSettings = {
  wpm: 200,
  fontSize: 32, // Adjusted default for better mobile fit
  fontFamily: ARABIC_FONTS[0].family,
  isBold: false,
  textAlign: 'right',
  readingMode: 'typewriter',
  brightness: 100,
  textColor: '#e2e8f0',
  highlightColor: '#38bdf8',
  backgroundColor: '#000000',
  glowIntensity: 0,
};

export const SAMPLE_TEXT = `الحمد لله والصلاة والسلام على رسول الله وعلى آله وصحبه أجمعين.

وبعد،

أهلاً بك في برنامج "القراءة البصرية". يسعدنا انضمامك إلينا في هذه الرحلة لتطوير مهاراتك القرائية.

كيف تستفيد من هذا البرنامج؟
صُمم هذا البرنامج ليعالج مشكلة التشتت أثناء القراءة ولزيادة سرعة استيعابك للنصوص. من خلال عرض النص كلمة تلو الأخرى أو بنمط الآلة الكاتبة، نساعد عينيك على التركيز في نقطة واحدة، مما يقلل من الإجهاد ويزيد من السرعة والكفاءة.

مميزات البرنامج التي ستعجبك:
- تحكم كامل في المظهر: اختر لون النص، الخلفية، ونوع الخط من بين مجموعة واسعة من الخطوط العربية والقرآنية.
- أنماط قراءة متنوعة: جرب نمط "تسليط الضوء" للتركيز الشديد، أو نمط "الآلة الكاتبة" لقراءة انسيابية، أو "الكلمات المتتابعة" لسرعة قصوى.
- تقنية بومودورو: استخدم المؤقت المدمج (أيقونة الساعة) لتقسيم وقت القراءة إلى جلسات تركيز وفترات راحة.
- اختصارات لوحة المفاتيح: لست بحاجة للفأرة! استخدم المسافة للتشغيل والإيقاف، والأسهم للتنقل بين الكلمات، وحرف E لفتح المحرر.

خطوات الاستخدام:
1. اضغط على زر "تحرير" (أو حرف E) لفتح المحرر، ثم الصق النص الذي تود قراءته.
2. اضغط على زر "قراءة" (أو مفتاح المسافة) لبدء العرض.
3. تحكم في السرعة وحجم الخط من الشريط السفلي أثناء القراءة لتجد الوتيرة المناسبة لك.

نتمنى لك تجربة ممتعة ومفيدة!`;

export const TRANSLATIONS = {
  ar: {
    appTitle: 'القراءة البصرية',
    library: 'المكتبة',
    shortcuts: 'اختصارات',
    mode: 'النمط',
    edit: 'تحرير',
    close: 'إغلاق',
    read: 'قراءة',
    pause: 'توقف',
    reset: 'إعادة',
    pasteText: 'ضع النص العربي هنا... اضغط Enter للقراءة.',
    enterHint: 'اضغط Enter للقراءة. Shift+Enter لسطر جديد.',
    words: 'كلمة',
    loading: 'جاري التحميل...',
    menu: {
      turath: 'تراث',
      quran: 'القرآن الكريم (تفسير)',
      dorar: 'الدرر السنية',
    },
    auth: {
      login: 'دخول',
      register: 'حساب جديد',
      username: 'اسم المستخدم',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      logout: 'تسجيل الخروج',
      submit: 'إرسال',
      haveAccount: 'لديك حساب بالفعل؟ سجل دخولك',
      noAccount: 'ليس لديك حساب؟ أنشئ حساباً',
      welcome: 'مرحباً',
      error: 'خطأ في البيانات',
      successRegister: 'تم إنشاء الحساب بنجاح',
      successLogin: 'تم تسجيل الدخول بنجاح'
    },
    settings: {
      speed: 'السرعة',
      wpm: 'كلمة/دقيقة',
      font: 'الخط',
      brightness: 'السطوع',
      size: 'الحجم',
      bold: 'غامق',
      quranic: '(قرآني)',
      color: 'اللون',
      highlightColor: 'لون الكلمة الأخيرة',
      backgroundColor: 'لون الخلفية',
      glow: 'توهج',
    },
    modes: {
      standard: 'قياسي',
      creative: 'إبداعي',
      experimental: 'تجريبي',
      typewriter: 'الآلة الكاتبة',
      rsvp: 'كلمة بكلمة (RSVP)',
      highlight: 'التركيز',
      spotlight: 'تسليط الضوء',
      magnify: 'المكبر',
      scroller: 'الملقن',
      karaoke: 'كاريوكي',
      bounce: 'ارتداد',
      pulse: 'نبض',
      blur: 'تمويه (Blur)',
      wavy: 'موجة (Wave)',
      glitch: 'تشويش (Glitch)',
      gradient: 'تدرج (Gradient)',
      outline: 'مفرغ (Outline)',
      neon: 'نيون (Neon)',
      mirror: 'مرآة (Mirror)',
      spread: 'تمدد (Spread)',
      flash: 'وميض (Flash)',
      dim: 'تعتيم (Dim)',
      boxed: 'إطار (Boxed)',
      underline: 'تسطير (Underline)',
      marker: 'قلم تمييز (Marker)',
      thick: 'سميك (Thick)',
      shake: 'اهتزاز (Shake)',
      jelly: 'هلام (Jelly)',
      swing: 'تأرجح (Swing)',
      slideDown: 'انزلاق (Slide Down)',
    },
    shortcutsModal: {
      title: 'اختصارات لوحة المفاتيح',
      pressKey: 'اضغط مفتاحاً...',
      space: 'مسافة',
      done: 'تم',
      desc: 'اضغط على مربع المفتاح للتعديل.',
      keys: {
        togglePlay: 'تشغيل / إيقاف',
        prevWord: 'الكلمة السابقة',
        nextWord: 'الكلمة التالية',
        incFontSize: 'تكبير الخط',
        decFontSize: 'تصغير الخط',
        incSpeed: 'زيادة السرعة',
        decSpeed: 'إنقاص السرعة',
        toggleFullscreenApp: 'ملء الشاشة (تطبيق)',
        toggleFullscreenReader: 'ملء الشاشة (قراءة)',
        incBrightness: 'زيادة السطوع (الشاشة)',
        decBrightness: 'إنقاص السطوع (الشاشة)',
        reset: 'العودة للبداية',
        nextFont: 'تغيير الخط',
        nextColor: 'تغيير اللون',
        incGlow: 'زيادة توهج النص',
        decGlow: 'إنقاص توهج النص',
        toggleBold: 'تغيير السماكة (غامق)',
        toggleLang: 'تغيير اللغة (عربي/إنجليزي)',
        nextMode: 'تغيير نمط القراءة',
        toggleEdit: 'فتح / إغلاق المحرر',
        clearText: 'مسح النص (في المحرر)',
        togglePomodoro: 'فتح / إغلاق مؤقت بومودورو',
        toggleLibrary: 'فتح / إغلاق قائمة المكتبة',
        toggleShortcuts: 'عرض قائمة الاختصارات',
        toggleStats: 'عرض الإحصائيات',
      }
    },
    readerBar: {
      progress: 'التقدم',
      timeRem: 'المتبقي',
      wpmShort: 'ك/د',
      wordsLeft: 'متبقية',
    },
    pomodoro: {
      title: 'مؤقت بومودورو',
      focus: 'تركيز',
      shortBreak: 'استراحة قصيرة',
      longBreak: 'استراحة طويلة',
      custom: 'تخصيص',
      enterTime: 'أدخل الدقائق:',
      start: 'ابدأ',
      pause: 'توقف',
      reset: 'إعادة ضبط',
      breakTime: 'وقت الاستراحة',
      relax: 'استرخِ قليلاً واستعد نشاطك',
      skipBreak: 'تخطي الاستراحة'
    },
    statistics: {
      title: 'إحصائيات القراءة',
      totalWords: 'مجموع الكلمات',
      totalTime: 'الوقت الكلي',
      avgSpeed: 'متوسط السرعة',
      sessions: 'الجلسات',
      encouragement: 'استمر في التقدم!',
      noData: 'لا توجد جلسات مسجلة بعد',
      words: 'كلمة',
      level1: 'مبتدئ',
      level2: 'قارئ مواظب',
      level3: 'قارئ نهم',
      level4: 'عالم',
      level5: 'حكيم',
    },
    sleepTimer: {
      title: 'مؤقت النوم',
      custom: 'تخصيص',
      set: 'تعيين',
      min15: '15 دقيقة',
      min30: '30 دقيقة',
      min60: '60 دقيقة',
      off: 'إيقاف',
    }
  },
  en: {
    appTitle: 'Visual Reading',
    library: 'Library',
    shortcuts: 'Shortcuts',
    mode: 'Mode',
    edit: 'Edit',
    close: 'Close',
    read: 'Read',
    pause: 'Pause',
    reset: 'Reset',
    pasteText: 'Paste your Arabic text here... Press Enter to start reading.',
    enterHint: 'Press Enter to read. Shift+Enter for new line.',
    words: 'words',
    loading: 'Loading...',
    menu: {
      turath: 'Turath',
      quran: 'The Holy Quran (Tafsir)',
      dorar: 'Dorar Saniyyah',
    },
    auth: {
      login: 'Login',
      register: 'Register',
      username: 'Username',
      email: 'Email',
      password: 'Password',
      logout: 'Logout',
      submit: 'Submit',
      haveAccount: 'Already have an account? Login',
      noAccount: 'No account? Create one',
      welcome: 'Welcome',
      error: 'Invalid Data',
      successRegister: 'Account created successfully',
      successLogin: 'Logged in successfully'
    },
    settings: {
      speed: 'Speed',
      wpm: 'WPM',
      font: 'Font Family',
      brightness: 'Brightness',
      size: 'Size',
      bold: 'Bold',
      quranic: '(Quranic)',
      color: 'Color',
      highlightColor: 'Last Word Color',
      backgroundColor: 'Background Color',
      glow: 'Glow',
    },
    modes: {
      standard: 'Standard',
      creative: 'Creative',
      experimental: 'Experimental',
      typewriter: 'Typewriter',
      rsvp: 'Single Word (RSVP)',
      highlight: 'Highlight Focus',
      spotlight: 'Focus Spotlight',
      magnify: 'Inline Magnifier',
      scroller: 'Teleprompter',
      karaoke: 'Karaoke Flow',
      bounce: 'Bounce',
      pulse: 'Pulse',
      blur: 'Blur Reveal',
      wavy: 'Wavy Flow',
      glitch: 'Glitch Tech',
      gradient: 'Gradient Fill',
      outline: 'Outline View',
      neon: 'Neon Glow',
      mirror: 'Mirror Reflection',
      spread: 'Spread Expand',
      flash: 'Flash Focus',
      dim: 'Extreme Dim',
      boxed: 'Boxed',
      underline: 'Underline',
      marker: 'Marker Highlight',
      thick: 'Thick Weight',
      shake: 'Shake',
      jelly: 'Jelly',
      swing: 'Swing',
      slideDown: 'Slide Down',
    },
    shortcutsModal: {
      title: 'Keyboard Shortcuts',
      pressKey: 'Press Key...',
      space: 'Space',
      done: 'Done',
      desc: 'Click on a key box to edit. Press the new key on your keyboard.',
      keys: {
        togglePlay: 'Play / Pause',
        prevWord: 'Previous Word',
        nextWord: 'Next Word',
        incFontSize: 'Increase Font Size',
        decFontSize: 'Decrease Font Size',
        incSpeed: 'Increase Speed',
        decSpeed: 'Decrease Speed',
        toggleFullscreenApp: 'Fullscreen App',
        toggleFullscreenReader: 'Fullscreen Reader (Focus)',
        incBrightness: 'Increase Brightness (Screen)',
        decBrightness: 'Decrease Brightness (Screen)',
        reset: 'Reset to Start',
        nextFont: 'Next Font',
        nextColor: 'Next Color',
        incGlow: 'Increase Text Glow',
        decGlow: 'Decrease Text Glow',
        toggleBold: 'Toggle Bold',
        toggleLang: 'Toggle Language (Ar/En)',
        nextMode: 'Next Reading Mode',
        toggleEdit: 'Open/Close Text Editor',
        clearText: 'Clear Text (Editor)',
        togglePomodoro: 'Open/Close Pomodoro Timer',
        toggleLibrary: 'Open/Close Library Menu',
        toggleShortcuts: 'Open/Close Shortcuts Help',
        toggleStats: 'Open/Close Statistics',
      }
    },
    readerBar: {
      progress: 'Progress',
      timeRem: 'Time Left',
      wpmShort: 'WPM',
      wordsLeft: 'words left',
    },
    pomodoro: {
      title: 'Pomodoro Timer',
      focus: 'Focus',
      shortBreak: 'Short Break',
      longBreak: 'Long Break',
      custom: 'Custom',
      enterTime: 'Enter minutes:',
      start: 'Start',
      pause: 'Pause',
      reset: 'Reset',
      breakTime: 'Break Time',
      relax: 'Relax and recharge',
      skipBreak: 'Skip Break'
    },
    statistics: {
      title: 'Reading Stats',
      totalWords: 'Total Words',
      totalTime: 'Total Time',
      avgSpeed: 'Avg Speed',
      sessions: 'Sessions',
      encouragement: 'Keep going!',
      noData: 'No sessions recorded yet',
      words: 'words',
      level1: 'Beginner',
      level2: 'Regular Reader',
      level3: 'Avid Reader',
      level4: 'Scholar',
      level5: 'Sage',
    },
    sleepTimer: {
      title: 'Sleep Timer',
      custom: 'Custom',
      set: 'Set',
      min15: '15 Minutes',
      min30: '30 Minutes',
      min60: '60 Minutes',
      off: 'Off',
    }
  }
};
